"""Turn content.json into the Jekyll site's content.

Writes _works/*.md (one per artwork), _data/*.yml (the index covers and the
three image galleries), and moves every image out of the archive into images/
under a name derived from what it is.

Rerunnable, and destructive on rerun: it clears _works/ and rewrites _data/.
Hand-edit a work and rerun this, and the edit is gone.
"""
import json, os, re, shutil, unicodedata

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARC = os.path.join(BASE, '_archive')

# The live site spells two things wrong, in both the category heading and the
# work's own title. Faithful is about the design, not about carrying typos.
FIX = {'Persian Minatures': 'Persian Miniatures', 'Mouring': 'Mourning'}

# Three illustrations were published with no title at all -- Squarespace shows
# an empty caption for them, and the only name they have is the file they were
# uploaded as. Keyed by that filename, inferred from it and from the book they
# belong to, and flagged so nobody mistakes them for confirmed titles.
UNTITLED = {
    'monkey+bridge.png': 'The Monkey Bridge',
    'monkey+bridge+cover.png': 'The Monkey Bridge (Cover)',
    'monkey+bridge+ship.png': 'The Monkey Bridge (Ship)',
}

SECTIONS = {
    '/paintings/': 'paintings',
    '/persian-miniatures/': 'miniatures',
    '/illustrations/': 'illustrations',
    '/posters/': 'posters',
}


def slug(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()
    return re.sub(r'-+', '-', re.sub(r'[^a-z0-9]+', '-', s.lower())).strip('-')


def yaml(value):
    return json.dumps(value, ensure_ascii=False)


content = json.load(open(os.path.join(ARC, 'content.json')))


def archived(url):
    import urllib.parse
    name = urllib.parse.unquote(url.rsplit('/', 1)[-1]).replace('+', ' ')
    return os.path.join(ARC, 'images', f"{url.rsplit('/', 2)[-2]}-{name}".replace(' ', '-'))


used = set()


def place(url, folder, name):
    """Move an archived image to images/<folder>/<name>.<ext>, uniquely."""
    ext = os.path.splitext(archived(url))[1].lower()
    n, base = 2, name
    while (folder, name) in used:
        name, n = f'{base}-{n}', n + 1
    used.add((folder, name))
    rel = f'/images/{folder}/{name}{ext}'
    dest = os.path.join(BASE, rel.lstrip('/'))
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    src = archived(url)
    if os.path.exists(src) and not os.path.exists(dest):
        shutil.move(src, dest)
    return rel


works_dir = os.path.join(BASE, '_works')
data_dir = os.path.join(BASE, '_data')
os.makedirs(works_dir, exist_ok=True)
os.makedirs(data_dir, exist_ok=True)
for f in os.listdir(works_dir):
    os.remove(os.path.join(works_dir, f))

# ------------------------------------------------------------ the sections

sections = []
for cat in content['categories']:
    sid = SECTIONS[cat['url']]
    cover = content['covers'][cat['url']]
    name = FIX.get(cat['title'], cat['title'])
    sections.append({
        'id': sid,
        'name': name,
        'url': cat['url'],
        'cover': place(cover['image'], 'covers', sid),
        'count': cover['count'],
        'description': [FIX.get(p, p) for p in cat['description']],
    })

    for order, w in enumerate(cat['works'], 1):
        # An untitled work is looked up by the file it was uploaded as. Falling
        # back to the bare filename keeps a new one from silently colliding
        # with another untitled piece and overwriting it.
        upload = w['url'].rsplit('/', 1)[-1]
        review = not w['title']
        title = (w['title'] and FIX.get(w['title'], w['title'])) \
            or UNTITLED.get(upload) or os.path.splitext(upload)[0].replace('+', ' ')
        image = place(w['url'], 'works', slug(title))

        fm = ['---', f'title: {yaml(title)}', f'category: {sid}', f'order: {order}',
              f'image: {image}']
        if w['width']:
            fm += [f'width: {w["width"]}', f'height: {w["height"]}']
        if w['note']:
            # "16 × 20 — Acrylic", as Fahimeh wrote it.
            fm.append(f'note: {yaml(w["note"])}')
        # Price is data. `show_prices` in _config.yml decides whether it renders.
        fm.append(f'price: {w["price"]}' if w['price']
                  else '# price:  # never had one on Squarespace')
        if review:
            fm.append('needs_review: true  # title inferred from filename; confirm with Fahimeh')
        fm += ['---', '']
        open(os.path.join(works_dir, f'{sid}-{slug(title)}.md'), 'w').write('\n'.join(fm))

with open(os.path.join(data_dir, 'sections.yml'), 'w') as f:
    f.write('# Generated by _archive/generate.py. The four sections of the Collection,\n'
            '# in the order the old site showed them, with the cover each one used.\n')
    for s in sections:
        f.write(f'- id: {s["id"]}\n  name: {yaml(s["name"])}\n  url: {s["url"]}\n')
        f.write(f'  cover: {s["cover"]}\n  count: {s["count"]}\n  description:\n')
        for p in s['description']:
            f.write(f'    - {yaml(p)}\n')

# ----------------------------------------------------------- the galleries


def write_gallery(filename, folder, images, note):
    rows = []
    for i, im in enumerate(images, 1):
        caption = FIX.get(im['caption'], im['caption'])
        # A caption that is just the upload filename is noise, not a caption.
        if re.search(r'\.(png|jpe?g)$', caption, re.I) or re.fullmatch(r'[\d\-_]+', caption):
            caption = ''
        rows.append({'image': place(im['url'], folder, slug(caption) or f'{folder}-{i:02}'),
                     'caption': caption})
    with open(os.path.join(data_dir, filename), 'w') as f:
        f.write(f'# Generated by _archive/generate.py. {note}\n')
        for r in rows:
            f.write(f'- image: {r["image"]}\n  caption: {yaml(r["caption"])}\n')
    return len(rows)


counts = {
    'gallery.yml': write_gallery('gallery.yml', 'gallery', content['gallery'],
                                 'The Gallery page slideshow.'),
}
for block in content['classes']:
    name = f'classes_{block["kind"]}.yml'
    counts[name] = write_gallery(name, 'classes', block['images'],
                                 f'The Classes page {block["kind"]}.')
for block in content['profile']:
    counts['profile.yml'] = write_gallery('profile.yml', 'profile', block['images'],
                                          'The Profile page slideshow.')

for s in sections:
    print(f'  {s["id"]:14} {s["count"]:3} works')
for k, v in counts.items():
    print(f'  {k:24} {v:3} images')
